#!/bin/bash
#BSUB --nnodes 1
#BSUB -q pbatch


## COMMAND: bsub -o output -e error script

#get list of xl compilers

version_string="xl/2018.04.29    xl/2019.04.19    xl/2019.12.23                xl/2020.08.13-cuda-11.0.2    xl/2020.09.17-cuda-11.0.2    xl/2020.11.12-cuda-11.1.1             xl/2021.03.11-cuda-11.1.0         xl/2021.03.11
   xl/2018.05.18    xl/2019.06.12    xl/2020.03.18                xl/2020.08.13                xl/2020.09.17                xl/2020.11.12-cuda-11.2.0-beta        xl/2021.03.11-cuda-11.1.1
   xl/2018.11.26    xl/2019.08.20    xl/2020.06.25-cuda-11.0.2    xl/2020.08.24-cuda-11.0.2    xl/2020.11.12-cuda-11.0.2    xl/2020.11.12                         xl/2021.03.11-cuda-11.2.0-beta
   xl/2019.02.07    xl/2019.12.16    xl/2020.06.25                xl/2020.08.24                xl/2020.11.12-cuda-11.1.0    xl/2021.03.11-cuda-11.0.2     xl/2021.03.11-cuda-11.2.0"


for COMPILERVERSION in $version_string
do

echo Loading compiler ${COMPILERVERSION}
module load $COMPILERVERSION

BUILDDIR="build-$COMPILERVERSION"

mkdir BUILDDIR
cd BUILDDIR

cmake -DENABLE_OPENMP=On -DENABLE_TARGET_OPENMP=On ..
make test

mkdir 
done

